Practice numpy with the help of Array

In [4]:

import numpy as np

In [5]:
df = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
df

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [6]:
df=np.array([1,2,3,4,np.nan,6,7],dtype='float')
df

array([ 1.,  2.,  3.,  4., nan,  6.,  7.])

In [7]:
df1 = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]]
)
df1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [8]:
df.shape

(7,)

In [9]:
df.dtype

dtype('float64')

In [10]:
df= df +5
df

array([ 6.,  7.,  8.,  9., nan, 11., 12.])

In [11]:
df.max()


nan

In [12]:
df.mean()

nan

In [13]:
df.min()

nan

In [14]:
print(np.sqrt(df))

[2.44948974 2.64575131 2.82842712 3.                nan 3.31662479
 3.46410162]


In [15]:
df.T

array([ 6.,  7.,  8.,  9., nan, 11., 12.])

In [16]:
df[2]=34


In [17]:
df

array([ 6.,  7., 34.,  9., nan, 11., 12.])

In [18]:
# np.concatenate((df1 , df.ravel()))

np.concatenate((df , df1.ravel()))

array([ 6.,  7., 34.,  9., nan, 11., 12.,  1.,  2.,  3.,  4.,  5.,  6.,
        7.,  8.,  9., 10., 11., 12.])

In [20]:
newdf=np.random.rand(3,4)
newdf

array([[0.62499237, 0.66992372, 0.77380931, 0.85566736],
       [0.4532428 , 0.12697823, 0.86388989, 0.30319504],
       [0.60878753, 0.54491277, 0.58769993, 0.08617514]])